config/routes.rb
Rails.application.routes.draw do
  resources :workers
  resources :phases
  devise_for :users
  resources :projects
  root 'home#index'
  post "/phases/:id" => "phases#pay_phase"
  get "/choose_worker/:id" => "phases#choose_worker", as: :choose_worker
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, :total_price,  presence: true
  validates :description, presence: true, length: { :minimum => 5 }

  belongs_to :user
  has_many :phases, dependent: :destroy
  def to_s
    title
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @phases = @project.phases
    @project.total_price = @project.phases.to_a.sum(&:price)
    @project.save
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description, :total_price)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@project) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :description
    = f.input :total_price

  .form-actions
    = f.button :submit

app/views/projects/_project.html.haml
.card
  .card-header
    .fa.fa-book
    = link_to project.title, project_path(project)
  .card-body
    = project.description
  .card-footer
    .far.fa-clock
    = project.created_at.strftime('%d-%b-%Y')
    .row
    .fa.fa-user
    = project.user
  .card-footer
    .text-center
      Total price: 
      = number_to_currency(project.total_price)
  .card-footer
    Number of phases in this project:
    .fa.fa-book
    = project.phases.count
  .card-footer
    = link_to 'Show', project, class: 'btn btn-sm btn-primary'
    = link_to 'Edit', edit_project_path(project), class: 'btn btn-sm btn-warning'
    = link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/projects/edit.html.haml
.card
  .card-header
    %h1 Editing project
  .card-body
    = render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 All Projects

.card-columns
  - @projects.each do |project|
    = render 'projects/project', project: project

%br

= link_to 'New Project', new_project_path, class: 'btn btn-sm btn-info'

app/views/projects/new.html.haml
.card
  .card-header
    %h1 New project
  .card-body
    = render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
= link_to 'Projects', projects_path
\/
= link_to @project.title, project_path(@project)
%p
.row
  .col-lg-6
    = render 'projects/project', project: @project

    = link_to "Add Workers", new_worker_path, class: 'btn btn-sm btn-info'
  .col-lg-6
    = link_to 'Add phase', new_phase_path(project_id: @project.id), class: 'btn btn-sm btn-primary'
    %p
    - @phases.each do |phase|
      = render 'phases/phase', phase: phase
      %p

%hr
= link_to 'Edit', edit_project_path(@project), class: 'btn btn-sm btn-primary'
\|
= link_to 'Back', projects_path, class: 'btn btn-sm btn-info'