config/routes.rb
Rails.application.routes.draw do
  resources :workers
  resources :phases
  devise_for :users
  resources :projects
  root 'home#index'
  post "/phases/:id" => "phases#pay_phase"
  get "/choose_worker/:id" => "phases#choose_worker", as: :choose_worker
end

app/models/worker.rb
class Worker < ApplicationRecord
  validates :name, :service, :price, :worker_type, presence: true

  WORKER_TYPES = [:Moler, :Keramicar, :Zidar, :Assembler]
  def self.worker_types
    WORKER_TYPES.map { |worker_type| [worker_type, worker_type] }
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: %i[ show edit update destroy ]

  # GET /workers or /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1 or /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers or /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: "Worker was successfully created." }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1 or /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: "Worker was successfully updated." }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1 or /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: "Worker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def worker_params
      params.require(:worker).permit(:name, :service, :price, :worker_type)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@worker) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :service
    = f.input :price
    = f.label :service
    = f.select :worker_type, Worker.worker_types, {include_blank: true}, class: "form-control  form-control-sm"
    
  .form-actions
    = f.button :submit

app/views/workers/edit.html.haml
%h1 Editing worker

= render 'form'

= link_to 'Show', @worker
\|
= link_to 'Back', workers_path

app/views/workers/index.html.haml
%h1 Listing workers

%table.table
  %thead
    %tr
      %th Name
      %th Service
      %th Price
      %th Work Type
      %th
      %th
      %th

  %tbody
    - @workers.each do |worker|
      %tr
        %td= worker.name
        %td= worker.service
        %td= worker.price
        %td= worker.worker_type
        %td= link_to 'Show', worker
        %td= link_to 'Edit', edit_worker_path(worker)
        %td= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Worker', new_worker_path

app/views/workers/new.html.haml
%h1 New worker

= render 'form'

= link_to 'Back', workers_path

app/views/workers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @worker.name
%p
  %b Service:
  = @worker.service
%p
  %b Price (per hour):
  = @worker.price

= link_to 'Edit', edit_worker_path(@worker)
\|
= link_to 'Back', workers_path