config/routes.rb
Rails.application.routes.draw do
  resources :workers
  resources :phases
  devise_for :users
  resources :projects
  root 'home#index'
  post "/phases/:id" => "phases#pay_phase"
  get "/choose_worker/:id" => "phases#choose_worker", as: :choose_worker
end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
  before_action :set_phase, only: %i[ show edit update destroy pay_phase choose_worker]

  # GET /phases or /phases.json
  def index
    @phases = Phase.all
  end

  # GET /phases/1 or /phases/1.json
  def show
  end

  # GET /phases/new
  def new
    @phase = Phase.new
  end

  # GET /phases/1/edit
  def edit
  end

  # POST /phases or /phases.json
  def create
    @phase = Phase.new(phase_params)

    respond_to do |format|
      if @phase.save
        format.html { redirect_to @phase, notice: "Phase was successfully created." }
        format.json { render :show, status: :created, location: @phase }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  def pay_phase
    if @phase.price > 0

      @amount = (@phase.price * 100).to_i
      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )
      charge = Stripe::Charge.create(
        customer:    customer.id,
        amount:      @amount,
        description: 'Phase Payment',
        currency:    'usd'
      )
      @phase.price -= @phase.price
      @phase.project.total_price -= @phase.price
      @phase.save!
      # @enrollment = current_user.buy_course(@phase)
      redirect_to phase_path(@phase), notice: "You are good!"
    else
      # @enrollment = current_user.buy_course(@course)
      redirect_to phase_path(@phase), notice: "You payed this phase!"
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_phase_path(@phase)
  end

  def choose_worker
    phase_type = @phase.phase_type
    case phase_type.to_s
    when "Painting"
      @workers = Worker.where(worker_type: "Moler")
    when "Polishing"
      @workers = Worker.where(worker_type: "Assembler")
    when "Building"
      @workers = Worker.where(worker_type: "Zidar")
    when "Tiles_job"
      @workers = Worker.where(worker_type: "Keramicar")
    else
      @workers = []
    end
  end

  # PATCH/PUT /phases/1 or /phases/1.json
  def update
    if params[:phase][:worker_name].present?
      @worker = Worker.find_by(name: params[:phase][:worker_name])
      @phase.update_column(:worker_name, @worker.name)

      hours_to_complete= (@phase.end_time.to_time - @phase.start_time.to_time)/ 1.hours

      worker_price = @worker.price.to_i * hours_to_complete
      @phase.update_column(:price, worker_price)
    end
    respond_to do |format|
      if @phase.update(phase_params)
        format.html { redirect_to @phase, notice: "Phase was successfully updated." }
        format.json { render :show, status: :ok, location: @phase }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phases/1 or /phases/1.json
  def destroy
    @phase.destroy
    respond_to do |format|
      format.html { redirect_to phases_url, notice: "Phase was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phase
      @phase = Phase.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def phase_params
      params.require(:phase).permit(:phase_title, :content, :project_id, :price, :phase_type, :worker_id, :start_time, :end_time, :worker_name)
    end
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/views/phases/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@phase) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :phase_title
    = f.input :content
    = f.input :price
    = f.label :job_type
    = f.select :phase_type, Phase.phase_types, {include_blank: true}, class: "form-control  form-control-sm"
    = f.input :project_id, input_html: {value: @phase.project_id || params[:project_id]}, as: :hidden
    = f.input :start_time
    = f.input :end_time




  .form-actions
    = f.button :submit

app/views/phases/_phase.html.haml
.card
  .card-header
    = link_to phase.phase_title, phase
  .card-body
    = phase.content
  .card-footer
    .text-center
      = number_to_currency(phase.price)
  .card-footer
    = phase.phase_type
  .card-footer
    Start time
    = phase.start_time
  .card-footer
    End phase
    = phase.end_time
  .card-footer
    = link_to 'Edit', edit_phase_path(phase), class: 'btn btn-sm btn-warning'
    = link_to 'Destroy', phase, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
  .card-footer
    -if phase.worker_name.present?
      Worker name: 
      = link_to phase.worker_name, worker_path(phase.worker_name)
    -else
      = link_to 'Add worker', choose_worker_path(phase), class: 'btn btn-sm btn-warning'
  - if phase.price > 0
    .card-footer
      .fa.fa-lock
        = form_tag phase do
          %script.stripe-button{"data-amount" => "#{(phase.price * 100).to_i}",
                                  "data-description" => "#{phase.phase_type} (#{number_to_currency phase.price})",
                                  "data-email" => "#{current_user.email}",
                                  "data-key" => "pk_test_51IQHP8Gzoqhblu6l8RZOJVHSHtTeANBmIHdP2CjgefcorLh9LdOdTlyitRj23oED992jc1SBSKhlBTQ3gS3hGEzu00suT6ZQ2w",
                                  "data-locale" => "auto",
                                  :src => "https://checkout.stripe.com/checkout.js"}
  - else
    .card-footer
      = form_tag phase do
        = submit_tag "Phase payed", class: 'btn btn-lg btn-success disabled'

app/views/phases/choose_worker.html.haml
%h1 Choose Worker
- if @workers.any?
  = simple_form_for (@phase) do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

    .form-inputs
      = f.collection_radio_buttons :worker_name, @workers, :name, :name,  item_wrapper_tag: :div

    .form-actions
      = f.button :submit, "Choose worker", class: 'btn btn-info'
  %p
  %br
  Workers overview:
  %p
  - @workers.each do |worker|
    = link_to worker.name, worker_path(worker)
    Working price (Per hour):
    = number_to_currency(worker.price)
    %br
- else
  %p There's no workers for this job available

%hr

= link_to 'Show', @phase
\|
= link_to 'Back', phases_path

app/views/phases/edit.html.haml
%h1 Editing phase

= render 'form'

= link_to 'Show', @phase
\|
= link_to 'Back', phases_path

app/views/phases/index.html.haml
%h1 Listing phases

%table.table
  %thead
    %tr
      %th Phase title
      %th Content
      %th Project
      %th Price
      %th
      %th
      %th

  %tbody
    - @phases.each do |phase|
      %tr
        %td= phase.phase_title
        %td= phase.content
        %td= phase.project
        %td= phase.price
        %td= link_to 'Show', phase
        %td= link_to 'Edit', edit_phase_path(phase)
        %td= link_to 'Destroy', phase, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Phase', new_phase_path, class: 'btn btn-sm btn-primary'
= link_to 'Back', projects_path, class: 'btn btn-sm btn-info'

app/views/phases/new.html.haml
%h1 New phase

= render 'form'

= link_to 'Back', phases_path

app/views/phases/show.html.haml
%p#notice= notice

%h1
  %b Phase title:
  = @phase.phase_title
%p
  %b Content:
  = @phase.content
%p
  %b Project:
  = @phase.project

%p
  %b Phase type:
  = @phase.phase_type

%p
  %b End time:
  = @phase.end_time

%p
  %b Price:
  = number_to_currency(@phase.price)

- if @phase.worker_name.present?
  %b Worker ID:
  = @phase.worker_name
%p

= link_to 'Edit', edit_phase_path(@phase), class: 'btn btn-sm btn-primary'

= link_to 'Back', project_path(@phase.project), class: 'btn btn-sm btn-primary'